### ISSUE TITLE
style/ 광고주 페이지 intro ~ about 스타일 작업

### ISSUE THREAD

**Issue by marte113** [iri-wa-7team/iri-wa#18]
### 📃Description

> 광고주 페이지 섹션 구성 intro 부터 about 섹션 까지

### 📌Todo

- [ ] #19
- [ ] performance 섹션 추가
- [ ] about 섹션 추가
- [ ] 광고주 네비게이션 바 스크롤 기능  

### 📝ETC

> 기타사항
