### ISSUE TITLE
feat/ 광고주 페이지 Service 섹션 및 Reference 섹션

### ISSUE THREAD

**Issue by marte113** [iri-wa-7team/iri-wa#33]
### 📃Description

> 광고주 페이지 Service 섹션 및 Reference 섹션 스타일 추가

### 📌Todo

- [ ] Service 섹션 기본 스타일
- [ ] Service 섹션 아코디언 
- [ ] Service 섹션 아코디언 테이블 디자인. 
- [ ] Reference 섹션 기본 스타일
- [ ] Reference 섹션 수직 슬라이더
- [ ] Reference 섹션 수직 슬라이더 이미지 교체 기능

### 📝ETC

> 기타사항
